CREATE TABLE credit_application (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    credit_amount DOUBLE PRECISION NOT NULL,
                                    loan_amount INTEGER NOT NULL,
                                    user_income INTEGER NOT NULL,
                                    credit_load DOUBLE PRECISION NOT NULL,
                                    credit_rating INTEGER NOT NULL,
                                    status VARCHAR(255) NOT NULL
);